### ISSUE TITLE
Refinar

### ISSUE THREAD

**Issue by Durfan** [DestinyAscension/TP2017#2]
@DestinyAscension/axiom 

Jogo totalmente operacional e funcional no repositório. Falta agora fazer as firulas e criar um solver #3 decente.

**Comment by Taciofpra** [comment]
Pablo, acho que seria valido "traduzir" os codigos e adicionar comentarios pra melhorar a legibilidade, se quiser posso começar a fazer isso amanhã, tambem formatar para manter um padrão, vinicius pediu por exemplo pra evitar usar uma hora assim:
int função(){
e outra assim
int função()
{
pediu pra mantermos um padrão de formatação

**Comment by Durfan** [comment]
Cores adicionadas novamente.

**Comment by Durfan** [comment]
@DestinyAscension/axiom 

- Criado o branch para desenvolvimento ("Oblivion"); o master deve ser protegido como build final.
- Alguns comentários adicionados ao codigo

To do:
- [ ] Novo gerador para o jogo.
- [ ] Criar uma subrotina/funções de inicialiazação do jogo (Novo jogo, Load ou Continue, etc)
- [ ] Melhorar o algoritmo de dificuldade, atualmente ele e muito simples e não confiavel
`4< 1+(rand()%9)`
- [ ] Criar uma função para o tempo de jogo e a função para determinar o jogo ganho
- [ ]Melhorar imensamente o algoritmo de checagem de jogada, ele esta tosco e complicado.
`void GAME ( int game [][9], int l, int c, int n )`

Por enquanto e isso o que tenho em mente, vamos documentar todo o porecesso por aqui.

Valeu pessoal :)

**Comment by Durfan** [comment]
Funcao para  verificar a jogada foi adaptada e adicionada junto com uma funcao que verifica possiveis jogadas.

```
    int i;
    int linha_setor = 3*((x-1)/3);
    int coluna_setor = 3*((y-1)/3);
    int lin1 = (x+1)%3;
    int lin2 = (x+3)%3;
    int col1 = (y+1)%3;
    int col2 = (y+3)%3;

    if ( x<1 || y>9 ) return 0;

    /* Check for the value in the given row and column */
    for (i=0; i<9; i++) {
        if (grid[i][y-1].player == n) return 0;
        if (grid[x-1][i].player == n) return 0;
    }

    /* Check the remaining four spaces in this sector */
    if (grid[lin1+linha_setor][col1+coluna_setor].player == n) return 0;
    if (grid[lin1+linha_setor][col2+coluna_setor].player == n) return 0;
    if (grid[lin2+linha_setor][col1+coluna_setor].player == n) return 0;
    if (grid[lin2+linha_setor][col2+coluna_setor].player == n) return 0;

    if (grid[x-1][y-1].hide == 0) return 0;

    return 1;
```

**Comment by Durfan** [comment]
Codigo totalmente reescrito com ponteiros e com uma nova estrutura para o "grid de sodoku"... Nao tinha o menos sentido criar uma estrutura para cada elemento do grid... a estrutura e o tabuleiro. Ainda a fazer... tentar utilicar fwrite() e fread() para salvar e dar o load nos arquivos, nao tem necessidade de dezenas de loops toda vez que precisarmos copiar variaveis.

E claro, corrigir alguns bugs e terminar a funcao win().
