### ISSUE TITLE
Bugs Windows v0.1.2

### ISSUE THREAD

**Issue by Taciofpra** [DestinyAscension/TP2017#32]
1. Crash que acontece ao completar um jogo pelo modo palmeiras, ocorre em aprox 10% das vezes
2. Arquivo de score board original aparentemente corrompido:
 ```
Melhores Tempos

 1 - Tacio      19s
 2 - ßú■  &4w 0s
 3 - §i/w<$4w\·a        0s
 4 - DE0w       0s
 5 - Ç@        -10722963649673333000000000000000000000000000000000000000000000000000000000000000000000000000000000000s
```
3. apos marcar a primeira vez na score board o jogo não me da mais a opção de marcar um novo tempo melhor ou pior que o anterior, nem reiniciando o programa, só oferece a opção apos resetar o arquivo de score

**Comment by Durfan** [comment]
Se nao me engano o problema esta no momento que ele tenta substituir os dados, qt aos valores creio que e uma falha basica na logica. Vou refazer essa funcao do zero.

https://github.com/DestinyAscension/TP2017/blob/7a50e10ae5d20c64bbcd1c5313f4d87f27c2af63/sudoku.c#L513

**Comment by Durfan** [comment]
O arquivo nao esta corrompido, o problema e que esta sendo escrito lixo no txt. A estrutura nao foi iniciada, e como nao existia o arquivo ele criou um com lixo.
