### ISSUE TITLE
Função de tempo de jogo

### ISSUE THREAD

**Issue by Durfan** [DestinyAscension/TP2017#7]
Criar a função que define e retorna o tempo de jogo.

Exemplo:
```
clock_t begin = clock();

/* here, do your time-consuming job */

clock_t end = clock();
double time_spent = (double)(end - begin) / CLOCKS_PER_SEC;
```

**Comment by Taciofpra** [comment]
#include <stdio.h>
#include <time.h>
 

void tecla_parar()  /*para implementar no codigo que Pablo ja fez podemos chamar essa função
depois que o verificador do sudoku validar a resolução*/
{
    printf("Jogo Iniciado! \n");
    printf("Aperte ENTER para parar o jogo \n");
    while(1)
    {
        if (getchar())
            break;
    }
    printf("Jogo Concluido \n");
}
 

int main()
{
   
    clock_t t;
    t = clock();
    tecla_parar();
    t = clock() - t;
    double tempo_de_jogo = ((double)t)/CLOCKS_PER_SEC; // em segundos
 
    printf("tecla_parar() took %f seconds to execute \n", tempo_de_jogo);
    return 0;
}

**Comment by Durfan** [comment]
https://github.com/DestinyAscension/TP2017/blob/324f2e611008790dd18317df6f0ead9852178730/sudoku.c#L112

**Comment by Durfan** [comment]
Operacional.
